### PR TITLE
Updated to remove the deprecated .count

### PR DESCRIPTION
**Pull request by Mattchewone**
Replaced with the faster version `estimatedDocumentCount`

### CODE REVIEW

**Comment by daffl** [comment]
Great, thank you!

**Comment by matiaslopezd** [comment]
@daffl Hi!

How I can make a faster count in MongoDB with feathers-mongoose?

> Replaced with the faster version `estimatedDocumentCount`

How use `estimatedDocumentCount`?

**Comment by daffl** [comment]
You can set `useEstimatedDocumentCount` in the `options`.

**Comment by matiaslopezd** [comment]
Like this?

```js
context.params.mongoose = {
   useEstimatedDocumentCount: true
}
```

**Comment by matiaslopezd** [comment]
Is a good options if I need count more than 30,000 per month records in range of one year?

I mean `30,000 * 12`

**Pull request merged**
