### PR TITLE
Handled collation param for case insensitive indexes

### PR DESCRIPTION
**Pull request by superbarne**
Is the same pr as #218 but ready to merge.

### CODE REVIEW

**Comment by daffl** [comment]
This looks good, thank you for updating. Is this a new feature (that should be documented) or a bugfix?

**Comment by superbarne** [comment]
I think its a feature. We can insert the same docs as in feathers-mongoose
https://github.com/feathersjs-ecosystem/feathers-mongodb#collation-support

**Comment by superbarne** [comment]
I have updated the README so it documents this new feature.

**Comment by daffl** [comment]
Thank you! Released as v6.2.0

**Pull request merged**
