### PR TITLE
Provide option to set max limit for count when using paging

### PR DESCRIPTION
**Pull request by dinodeSimon**
### Summary

(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))

- [X] Tell us about the problem your pull request is solving.

When using a moderately large collection (6m documents) with paging enabled the time taken to get a count even with no query parameters is significant. This PR adds an optional upper record limit to the options for a service to improve performance with large collections

- [X] Are there any open issues that are related to this?
No
- [X] Is this PR dependent on PRs in other repos?
No

If so, please mention them to keep the conversations linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

There is already an option included to use estimate document count but this only returns the total number of documents in a collection so as soon as you add any criteria to the find the number is wrong and since it is used for paging it implies that you can skip to pages that don't exist. If this option is disabled the aggregation to get the count is extremely slow. As an example i'm using the IMDB database loaded into Mongo which has about 6m titles. If you trace the commands issued to mongoose it takes 0ms to return the 10 results requested as part of the page and then 3 seconds to get the count on my local machine. Adding any parameters to the query causes this to slow down even further.

Setting this limit on the count to something like 50,000 cause the result to come back in milliseconds. The limit that gets returned will still be incorrect if there are more results than this but at least it will be correct if there are less results whereas using useEstimatedDocumentCount it will always be wrong if any query parameters are used. 

If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).

Thanks for contributing to Feathers! :heart:

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the pull request! One question I usually ask when adding a new option (that has to be documented, tested, maintained and people have to know about) is if this would also be possible with what Feathers already provides, in this case a hook like this:

```js
const maxTotalLimit = (limit = 50000) => context => {
  const { query = {} } = context.params;

  if (query.$limit !== undefined) {
    context.params.query = {
      ...query,
      $limit: limit
    }
  }
}
```

**Comment by daffl** [comment]
As a performance side note: For larger collections it makes usually sense to limit the allowed query parameters and put [an index](https://docs.mongodb.com/manual/indexes/) on the ones that are allowed. This should speed up queries significantly.

**Comment by dinodeSimon** [comment]
Thanks for following up David. 

The limit on the query is already happening as part of the pagination (I think).  The problem is that two queries get issued to mongo. The limit gets passed through to the one that gets the data but doesn't get passed through to the one that does the count. 

The example below is a query looking at title-type: "movie" and deletedAt: null which has a composite index.

This first command is the count which Mongo does by issuing an aggregation with the parameters for the search and it does a group and sum operation on.
https://docs.mongodb.com/manual/reference/method/db.collection.countDocuments/#behavior
This takes 3154ms to get the count of 522988 documents out of the 6m+ documents in the collection.


2019-08-15T11:35:53.531+1000 I COMMAND [conn177] command xmsserver.titles command: aggregate { aggregate: "titles", pipeline: [ **{ $match: { title-type: "movie", deletedAt: null } }, { $group: { _id: 1, n: { $sum: 1 } }** } ], cursor: {}, lsid: { id: UUID("198f9667-716a-40af-829f-d585d88e410d") }, $db: "xmsserver" } planSummary: IXSCAN { title-type: 1, deletedAt: 1 } keysExamined:522988 docsExamined:522988 cursorExhausted:1 numYields:4133 nreturned:1 reslen:129 locks:{ Global: { acquireCount: { r: 4135 } }, Database: { acquireCount: { r: 4135 } }, Collection: { acquireCount: { r: 4135 } } } protocol:op_msg 3154ms

The second query it issues is to actually get the data. This one does get the limit thats passed through which in this case is the page of 10 after skipping the first 40 results. This part of the query takes 0ms to complete.

2019-08-15T11:35:53.533+1000 I COMMAND [conn180] command xmsserver.titles command: find { find: "titles", filter: { title-type: "movie", deletedAt: null }, projection: {}, skip: 40, limit: 10, returnKey: false, showRecordId: false, $db: "xmsserver" } planSummary: IXSCAN { title-type: 1, deletedAt: 1 } keysExamined:50 docsExamined:50 cursorExhausted:1 numYields:0 nreturned:10 reslen:4162 locks:{ Global: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { r: 1 } } } protocol:op_msg 0ms

The result on the count is actually worse if it just get the whole collection since it hits all 6m keys on the index to get the count.

The PR basically adds the limit to the count so that it gives up after hitting the maximum limit and returns faster. 


Appreciate the thoughts on the indexes as well. We have hook that checks incoming queries to ensure that no sorts or queries can happen on fields that aren't indexed in Mongo to avoid full collection scans.

**Comment by jamesjnadeau** [comment]
IMHO, this is a special case option that is not going to be used by most people. I would recommend this be implemented by over-loading/riding the default behavior of this adapter. I don't believe this is a data access method we should be steering people towards.

If your total is always wrong, why even have it? Why even do this operation to get a count? Couldn't you just do a direct limit to 50k and move on?

**Comment by daffl** [comment]
Agreed. Thank you again for the PR but for the reasons mentioned before, I think this should (and can) be done through a hook or by extending the adapter.

**Pull request closed without merging**
