### PR TITLE
Incorrect results when multi-patchting properties included in data and query.

### PR DESCRIPTION
**Pull request by RubyRubenstahl**
This PR is in relation to the issue originally reported [here]( https://github.com/feathersjs/feathers/issues/1221). 

## The problem
When performing a patch with a `null` id a property included in the query is being changed in the patch `data`, the patch happens successfully but an empty array is returned.

For example:
```JS
const data = await pets.patch(null, { name: 'Spot' }, { query: { name: 'Rufus' } });
```
changes Rufus to Spot in the database, but the return value is `[]`.

I found that, in the `_patch` function of `service.js`, there is a section labeled with
```JS
    // NOTE (EK): We need this shitty hack because update doesn't
    // return a promise properly when runValidators is true. WTF!
```
where the patch is performed, then a `_getOrFind` is run with the the original params to retrieve the updated afteward. 

Because the original query is re-used, but the data has been changed, the query doesn't find anything. 

## Proposed solution
I'm not sure if this is the best route to take because it is a hack on top of a hack, but the proposed change rebuilds the query, replacing anything that was both in the query and in data with the value from the data, using this "hybrid" query for the `_getOrFind` call after the patch. 

I've also added a test both to illustrate the problem and test the proposed solution.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you, I think this looks good. Can you update with the latest master? The tests should pass then.

**Comment by RubyRubenstahl** [comment]
Sorry, not quite sure what you mean by update with latest master. 

This is branched from the current master. 

I'm still getting used to github workflow :)

**Comment by daffl** [comment]
I just updated it to fix the tests. In your branch you can do

```
git pull git@github.com:feathersjs-ecosystem/feathers-mongoose.git master
git push origin patch-issue
```

**Comment by daffl** [comment]
Allright, with your test I was able to create a fix that works with the existing tests in #330

**Pull request closed without merging**
