### PR TITLE
add query modifier function support.

### LINKED ISSUE #407: Support specifying which replica set to read from
Been thinking about optimising how my backend handles its connection with the database.

One of the main things you can do is set the read preference to make use of your mongo clusters secondary replica sets for read operations. The main issue with this approach is that the replica sets may be delayed in getting the latest data, so globally specifying to use a secondary replica set is off the books if your application needs to do exact point-in-time finds on some services.

I was looking into this and spotted this in mongoose, basically, you can set the read preference for a specific query.
https://mongoosejs.com/docs/api.html#query_Query-read

What would be nice is the ability to specify this on a per-service and per-request level. e.g. have a service option `readPreference` that sets the default read preference for the service, and allow `$readPreference` to be set in the params of a find/get request to override the default for the service/mongoose.

I'm not certain about other adaptors and whether their databases support replica sets and querying them, what is implemented should be optional for other adaptors to implement, and certainly not break them if someone mistakenly tries to specify the read preference.

I don't mind making a PR for this if it sounds like a good idea.

### PR DESCRIPTION
**Pull request by mrfrase3**
## Query Modifiers

Sometimes it's important to use an unusual Mongoose Query method, like [specifying whether to read from a primary or secondary node,](https://mongoosejs.com/docs/api.html#query_Query-read) but maybe only for certain requests.

You can access the internal Mongoose Query object used for a find/get request by specifying the queryModifier function. It is also possible to override that global function by specifying the function in a requests params.

```js
// Specify a global query modifier when creating the service
app.use('/messages', service({
  Model,
  queryModifier: (query, params) => {
    query.read('secondaryPreferred');
  },
  queryModifierKey: '__queryModifier__' // default is 'queryModifier'
}));

app.service('messages').find({
  query: { ... },
}).then((result) => {
  console.log('Result from secondary:', result)
});

// Override the modifier on a per-request basis
app.service('messages').find({
  query: { ... },
  __queryModifier__: (query, params) => {
    query.read('primaryPreferred');
  }
}).then((result) => {
  console.log('Result from primary:', result)
});

// Disable the global modifier on a per-request basis
app.service('messages').find({
  query: { ... },
  __queryModifier__: false
}).then((result) => {
  console.log('Result from default option:', result)
});
```

resolves #407

### CODE REVIEW

**Comment by daffl** [comment]
Sorry almost missed this. It looks good to mee. Can you resolve the conflict and I can get a new minor version out.

**Comment by mrfrase3** [comment]
Hey @daffl,

I've fixed the merge conflict, I also updated the type definition.

**Comment by daffl** [comment]
Thank you! Just to clarify, `__queryModifier__` is just an example for changing the key and it's `params.queryModifier` by default right?

**Comment by mrfrase3** [comment]
Yes, correct. queryModifier is the default

**Comment by daffl** [comment]
Release as v8.5.0, thank you!

**Pull request merged**
