### PR TITLE
add option to customize findOne queries

### PR DESCRIPTION
**Pull request by marbemac**
Hi there, we are trying to solve the common use case of supporting "slugs" as well as "ids" in our API (similar to how Github does it). This means that most service methods need to support looking up an object by id or slug property. We'd love to use feathers-mongoose, but saw no easy way to solve this problem with the current options.

This, I'd like to propose a new service option, `findOneQuery`. findOneQuery is an optional function that is passed three arguments, `id`, `data`, and `params`. It should return the mongoose query object that will be used by service methods when performing lookups.

The default findOneQuery function simply returns the current default query object:

```js
{ [this.id]: id }
```

Here is an example of how to support lookup by id and slug equally (which is basically how we will be using it).

```js
app.use('/organizations', service({
    Model: Organization,
    findOneQuery: (id, data, params) => ({
        $or: [{
            _id: id
        }, {
            slug: id
        }]
    })
}))
```

I went ahead and refactored the tests a little bit to make sure all the existing methods are covered and support this. Now most of the tests run without findOneQuery set and with findOneQuery set.

Let me know what you think!

### CODE REVIEW

**Comment by daffl** [comment]
I've implemented slug functionality with hooks before (setting `hook.result` to skip the original `get`). I think something like

```js
app.service('organizations').hooks({
  before: {
    get(hook) {
      const query = {
        $or: [{
            _id: hook.id
        }, {
            slug: hook.id
        }]
      };

      return hook.service.find({
        query,
        paginate: false
      }).then(result => {
        if(result.length === 1) {
          hook.result = result[0];
        }

        return hook;
      });
    }
  }
});
```

Would do the same thing without having to modify the database adapter itself right?
In this case we could also use

```js
const query = { slug: hook.id };
```

And just continue to the original `get` if `slug` wasn't found. This might result in two DB calls for a get but I haven't found that an issue so far.

@eddyystop I thought there was a slug common hook but I could only find `setSlug`.

**Comment by marbemac** [comment]
Yeah, but we'd have to do that for remove, update, patch as well. By that point, it kind of feels like we're re-implementing the entire service.

**Comment by daffl** [comment]
I still think it can be implemented with a fairly simple hook for all cases by setting `hook.id`:

```js
function slugId(name, idField = '_id') {
  const methods = [ 'get', 'update', 'patch', 'remove' ];

  return function(hook) {
    if(methods.indexOf(hook.method) !== -1) {
      const query = {
        [name]: hook.id
      };

      return hook.service.find({
        query,
        paginate: false
      }).then(result => {
        if(result.length === 1) {
          hook.id = result[0][idField];
        }

        return hook;
      });
    }
  }
}
```

This can then be initialized for all services with

```js
app.hooks({
  before: slugId('slug')
});
```

Not that we don't appreciate the contribution but I'd prefer a generic hook for things like this since it'll work with all services. We are trying to keep database adapter specific functionality at a minimum since every change increases the maintenance overhead - in this case for example we'd really have to implement the same functionality for all other official database adapter as well.

**Comment by eddyystop** [comment]
@daffl There is only setSlug which deals with slugs in URLs. Ill create an issue for this in feathers-hooks-common.

**Comment by marbemac** [comment]
Totally understand the desire to not make changes to the API. However, doesn't that double the number of lookups in all cases? A find, and the adapter itself will do a findOne? Worst comes to worst we can maintain our own fork.

**Comment by marshallswain** [comment]
@daffl I think it's worth letting this adapter be different if it saves making an extra query.  Can't the other adapters be updated when the need arises, if ever.

**Comment by daffl** [comment]
You can still save the extra queries by using hooks.

```js
function modifyWithSlug(name) {
  return function(hook) {
    if(hook.id !== null) {
      const idField = hook.service.id;
      const query = {
        $or: [{
            [idField]: hook.id
        }, {
            [name]: hook.id
        }]
      };

      hook.id = null;
      hook.params.query = query;
    }
  }
}

function getWithSlug(name) {
  return function(hook) {
    const idField = hook.service.id;
    const query = {
      $or: [{
          [idField]: hook.id
      }, {
          [name]: hook.id
      }]
    };

    return hook.service.find({
      query,
      paginate: false
    }).then(result => {
      if(result.length === 1) {
        hook.result = result[0];
      }

      return hook;
    });
  }
}
```

Can be used like

```
const modify = modifyWithSlug('slug');
const get = getWithSlug('slug');

app.before({
  get,
  patch: modify,
  remove: modify,
  update: modify
});
```

and won't make any additional queries.

I'd really prefer a generic solution that works across all adapters mainly because I know the pain of maintaining and documenting them all and keeping shared functionality in sync. We should try to only add functionality to the adapters that can't be accomplished any other way and to me this use case is exactly what hooks are for.

**Comment by InstanceOfMichael** [comment]
Here's another option if you just want a small front-end helper:
```
import NotFound from '@feathersjs/errors';

export async function getWithSlug(service, slug) {
  const collection = await service.find({
    query: {
      slug,
      // deleted: { $ne: true },
      $limit: 1,
    },
  });

  if (collection.data[0]) {
    return collection.data[0];
  } else {
    throw new NotFound(`No record found matching slug ${slug}`);
  }
}
```

**Pull request closed without merging**
