### PR TITLE
Fix bug where regex fails in error-handler

### PR DESCRIPTION
**Pull request by cdimitroulas**
### Summary

The regex inside the `errorHandler` does not work correctly for string values. If a `Conflict` occurs in the database where two string values clash (such as the name `"Kate"` in the tests) then the `value` variable was equal to `"Kate""` before this fix (please notice the extra double quote in the string).

This PR fixes that issue. The test cases added fail before the modification to the regex.

### CODE REVIEW

**Comment by cdimitroulas** [comment]
I am unable to understand why the tests are failing on an unrelated test case to the code I have modified. If someone could explain this to me I am happy to go and make any required changes.

Although I am slightly confused as to how a change in this regular expression could cause the tests to fail so perhaps it's an issue with how I edited the error handler tests...

**Comment by daffl** [comment]
Thank you for the pull request @cdimitroulas! Looks like the error was a bug with a later version of MongoDB and how indexes for some tests were set up. It is fixed now so if you pull latest master and push it tests should pass.

**Comment by cdimitroulas** [comment]
All done!

**Comment by daffl** [comment]
Awesome, thank you. Released as v6.1.1

**Pull request merged**
